#ifndef ERRORCODE_HPP
# define ERRORCODE_HPP

enum ErrorCode {
	ERR_NONE = 0,
	ERR_DONOTHING,
	ERR_NOSUCHNICK = 401,
	ERR_NOSUCHCHANNEL = 403,
	ERR_TOOMANYCHANNELS = 405,
	ERR_UNKNOWNCOMMAND = 421,
	ERR_NONICKNAMEGIVEN = 431,
	ERR_ERRONEUSNICKNAME,
	ERR_NICKNAMEINUSE,
	ERR_NOTONCHANNEL = 442,
	ERR_USERONCHANNEL,
	ERR_NOTREGISTERED = 451,
	ERR_NEEDMOREPARAMS = 461,
	ERR_ALREADYREGISTRED,
	ERR_KEYSET = 467,
	ERR_CHANNELISFULL = 471,
	ERR_UNKNOWNMODE,
	ERR_INVITEONLYCHAN,
	ERR_BADCHANNELKEY = 475,
	ERR_BADCHANNAME = 479,
	ERR_CHANOPRIVSNEEDED = 482,
	ERR_INVALIDFILEPATH = 500,
	ERR_FILEERROR,
	ERR_FILENOTFOUND,
	ERR_ALREADYINGAME,
	ERR_NOTINGAME,
};

#endif