#ifndef RESPONSECODE_HPP
# define RESPONSECODE_HPP

enum ResposeCode {
	RPL_WELCOME = 1,
	RPL_CHANGEDNICK,
	RPL_PONG = 300,
	RPL_CHANNELMODEIS = 324,
	RPL_NOTOPIC = 331,
	RPL_TOPIC,
	RPL_INVITING = 341,
	RPL_NAMREPLY = 353,
	RPL_ENDOFNAMES = 366,
	RPL_INFO = 371
};

#endif