#ifndef RESPONSECODE_HPP
# define RESPONSECODE_HPP

enum ResposeCode {
	RPL_CHANNELMODEIS = 324,
	RPL_NOTOPIC = 331,
	RPL_TOPIC,
	RPL_INVITING = 341,
	RPL_NAMREPLY = 353,
	RPL_ENDOFNAMES = 366,
};

#endif